name: question_matching_game_example
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing of the example

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  question_matching_game:
    path: ../ # Points to the main plugin in the parent directory
  get: ^4.6.6 # Required by the plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true