name: matching_game
description: A Flutter plugin for an interactive drag-and-drop question-answer matching game supporting flexible data formats.
version: 0.1.0
homepage: https://github.com/allenmasud12/matching_game
repository: https://github.com/allenmasud12/matching_game
issue_tracker: https://github.com/allenmasud12/matching_game/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0